site_name: Snapdragon
repo_name: rbx-snapdragon
repo_url: https://github.com/roblox-aurora/rbx-snapdragon
nav:
    - Home: index.md
    - Installation:
        - Install for TypeScript: robloxts-install.md
        - Install for Lua: lua-install.md
    - Basic Usage: basic-usage.md
    # - Installation:
    #     - Install for TypeScript: robloxts-install.md
    #     - Install for Lua: lua-install.md
    # - Guide:
    #     - Events: events.md
    # - API Reference:
    #   - Net namespace: api-reference.md
    #   - Server Classes:
    #     - ServerEvent: class/NetServerEvent.md
    #     - ServerFunction: class/NetServerFunction.md
    #     - ServerThrottledFunction: class/NetServerThrottledFunction.md
    #     - ServerThrottledEvent: class/NetServerThrottledEvent.md
    #     - GlobalEvent: class/NetGlobalClientEvent.md
    #     - GlobalServerEvent: class/NetGlobalClientEvent.md
    #     - ServerAsyncFunction: class/NetServerAsyncFunction.md
    #   - Client Classes:
    #     - ClientEvent: class/NetClientEvent.md
    #     - ClientFunction: class/NetClientFunction.md
    #     - GlobalClientEvent: class/NetGlobalClientEvent.md
    #     - ClientAsyncFunction: class/NetClientAsyncFunction.md
theme:
    # feature:
    #   tabs: true
    name: material
    palette:
        primary: 'Grey'
        accent: 'Red'
    logo: 'https://assets.vorlias.com/i1/snapdragon.png'
markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.details:
    - pymdownx.inlinehilite:
    - pymdownx.tasklist:
    - pymdownx.superfences:
        preserve_tabs: true
    - codehilite:
          guess_lang: false
    - toc:
          permalink: true
#extra_css:
#  - 'styles/extra.css'
