[package]
name = "vorlias/snapdragon"
description = "Dragging library with snapping capabilities for Roblox UI"
version = "2.1.0"
license = "MIT"
authors = ["Vorlias"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"